CREATE DATABASE unzip_db;
GO

USE unzip_db;
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='kyc_document_unzip' AND xtype='U')
BEGIN
    CREATE TABLE kyc_document_unzip (
        KYC_UNZIP_ID NVARCHAR(36) PRIMARY KEY,
        CLIENT_ID NVARCHAR(255),
        DOCUMENT_LINK_ID NVARCHAR(255) NOT NULL,
        DOCUMENT_NAME NVARCHAR(255),
        DOCUMENT_TYPE NVARCHAR(100),
        PARENT_DOCUMENT_LINK_ID NVARCHAR(255),
        LST_UPD_TIME TIME DEFAULT CONVERT(TIME, GETDATE()),
        LST_UPD_DT DATE DEFAULT CONVERT(DATE, GETDATE()),
        DOCUMENT_PATH NVARCHAR(MAX),
        STATUS BIT,
        ERROR NVARCHAR(3000)
    );
END
GO
